import pandas as pd


abbreviations = {
    "Bridge": "BRG",
    "Child": "CHD",
    "Enemy": "ENM",
    "Father": "FTH",
    "Female connected kin": "FCK",
    "In-laws": "INL",
    "Jealousy": "JLS",
    "Mother": "MTH",
    "Rich": "RCH",
    "Road": "ROD",
    "Siblings": "SIB",
    "Town": "TWN",
    "Walk": "WLK",
    "Go": "GOO",
    "Work": "WRK",
    "Blind": "BND",
    "Crazy": "CRZ",
    "Fear": "FER",
    "Gather": "GTH",
    "Good": "GUD",
    "Hear": "HER",
    "Hide": "HID",
    "Measure": "MSR",
    "See": "SEE",
    "Shame": "SHM",
    "Think": "TNK",
    "Know": "KNW",
    "Black": "BLK",
    "Green": "GRN",
    "Yellow": "YLW",
    "Red": "RED",
    "Arm": "ARM",
    "Armpit": "AMP",
    "Arse": "ARS",
    "Back": "BCK",
    "Bark": "BRK",
    "Blood": "BLD",
    "Brain": "BRN",
    "Corner": "CNR",
    "Ear": "EAR",
    "Face": "FAC",
    "Fart": "FRT",
    "Foot": "FOT",
    "Genitals": "GNT",
    "Hair": "HAR",
    "Head": "HED",
    "Hiccup": "HCP",
    "Horn": "HRN",
    "Jaw": "JAW",
    "Knee": "KNE",
    "Liver": "LVR",
    "Lungs": "LNG",
    "Mouth": "MTH",
    "Nail": "NAL",
    "Navel": "NVL",
    "Neck": "NCK",
    "Nose": "NOS",
    "Piss": "PIS",
    "Ring": "RNG",
    "Shit": "SHT",
    "Side": "SID",
    "Sinew": "SNW",
    "Skin": "SKN",
    "Sneeze": "SNZ",
    "Snot": "SNT",
    "Spew": "SPW",
    "Spittle": "SPI",
    "Tail": "TAL",
    "Thigh": "THG",
    "Tit": "TIT",
    "Tooth": "TTH",
    "Wing": "WNG",
    "Under": "UND",
    "Between": "BTW",
    "Middle": "MID",
    "Dust": "DST",
    "Earth": "ERT",
    "Lake": "LKE",
    "Landslide": "LND",
    "Metal": "MTL",
    "Mud": "MUD",
    "Plain": "PLN",
    "Sand": "SND",
    "Dry": "DRY",
    "Early": "ERL",
    "Hail": "HAL",
    "Lightning": "LTN",
    "Mirror": "MRR",
    "Moon": "MON",
    "Night": "NGT",
    "Over": "OVR",
    "Rain": "RAN",
    "Rainbow": "RBW",
    "Shadow": "SHD",
    "Cloud": "CLD",
    "Sky": "SKY",
    "Star": "STR",
    "Sun": "SUN",
    "Thunder": "THN",
    "Today": "TDY",
    "Tomorrow": "TMR",
    "Wind": "WND",
    "Year": "YER",
    "Ashes": "ASH",
    "Burn": "BUR",
    "Charcoal": "CHR",
    "Fire": "FIR",
    "Firewood": "FWD",
    "Quench": "QNC",
    "Smoke": "SMK",
    "Drip": "DRP",
    "Wash": "WSH",
    "Agouti": "AGT",
    "Animal": "ANM",
    "Armadillo": "AMD",
    "Bat": "BAT",
    "Coati": "COT",
    "Cougar": "CGR",
    "Coyote": "CYT",
    "Deer": "DER",
    "Dog": "DOG",
    "Fox": "FOX",
    "Gopher": "GPH",
    "Green deer": "GDR",
    "Housecat post-contact": "HCT",
    "Jaguar": "JGR",
    "Kinkajou potos flavus": "KPF",
    "Monkey": "MNK",
    "Mountain cow": "MCW",
    "Mouse": "MUS",
    "Rat": "RAT",
    "Peccary": "PEC",
    "Possum": "PSM",
    "Rabbit": "RBT",
    "Skunk": "SKK",
    "Squirrel": "SQR",
    "Weasel": "WSL",
    "Bird": "BRD",
    "Buzzard": "BZD",
    "Crow/heron": "CRH",
    "Dove": "DOV",
    "Duck": "DCK",
    "Egg": "EGG",
    "Gizzard": "GZD",
    "Grackle": "GCK",
    "Hawk": "HWK",
    "Hummingbird": "HMB",
    "Nest": "NST",
    "Owl": "OWL",
    "Parrots": "PRT",
    "Quail": "QAL",
    "Quetzal": "QTZ",
    "Toucan": "TCN",
    "Turkey": "TRK",
    "Woodpecker": "WPK",
    "Boa": "BOA",
    "Rattlesnake": "RTS",
    "Iguana": "IGN",
    "Crawfish": "CWF",
    "Snail": "SNL",
    "Weevil": "WVL",
    "Dragonfly": "DGF",
    "Ant": "ANT",
    "Bedbug": "BDB",
    "Butterfly": "BTF",
    "Centipede": "CNT",
    "Cockroach": "CKR",
    "Cricket": "CKT",
    "Grasshopper": "GHP",
    "Cutworm": "CTW",
    "Flea": "FLE",
    "Fly": "FLY",
    "Green deerfly": "GDF",
    "Lightning bug": "LBG",
    "Locust": "LCS",
    "Louse": "LOU",
    "Scorpion": "SCR",
    "Skeeter": "SKE",
    "Spider": "SPD",
    "Tick": "TCK",
    "Wasp": "WSP",
    "Worm": "WRM",
    "Answer": "ANS",
    "Call": "CAL",
    "Yell": "YEL",
    "Shout": "SHT",
    "Dumb": "DMB",
    "Help": "HLP",
    "Lie": "LIE",
    "Deceive": "DCV",
    "Misdeed": "MSD",
    "Moan": "MON",
    "Name": "NAM",
    "Speak": "SPK",
    "Wait": "WAT",
    "Dance": "DNC",
    "Drum": "DRM",
    "Flute": "FLT",
    "Laugh": "LGH",
    "Play": "PLY",
    "Rattle": "RTL",
    "Sing": "SNG",
    "Change": "CHG",
    "Debt": "DBT",
    "Gift": "GFT",
    "Pay": "PAY",
    "Pet": "PET",
    "Put": "PUT",
    "Give": "GIV",
    "Stingy": "STG",
    "Take": "TKE",
    "Theft": "THF",
    "Trade": "TRD",
    "Bald": "BLD",
    "Break": "BRK",
    "Carry": "CRY",
    "Load": "LOD",
    "Clench": "CLH",
    "Cover": "CVR",
    "Cut": "CUT",
    "Dig": "DIG",
    "Grab": "GRB",
    "Hit": "HIT",
    "Hook": "HOK",
    "Loosen": "LSN",
    "Make": "MKE",
    "Mould": "MLD",
    "Paint": "PNT",
    "Peel": "PEL",
    "Pull": "PUL",
    "Push": "PSH",
    "Remain": "RMN",
    "Roll": "ROL",
    "Wrap": "WRP",
    "Scatter": "SCT",
    "Scrape": "SCP",
    "Scratch": "SCH",
    "Seated": "STD",
    "Spread": "SPR",
    "Stab": "STB",
    "Poke": "POK",
    "Straighten": "STN",
    "Strain": "STN",
    "Stretch": "STC",
    "Throw": "THW",
    "Shoot": "SHO",
    "Twist": "TWS",
    "Wipe": "WIP",
    "Axe": "AXE",
    "Blowgun": "BGN",
    "Fan": "FAN",
    "Griddle": "GDL",
    "Ladder": "LDR",
    "Quern": "QRN",
    "Spear": "SPE",
    "Staff": "STF",
    "Trap": "TRP",
    "Tumpline": "TMP",
    "Whetstone": "WHS",
    "House": "HSE",
    "Bed": "BED",
    "Braid": "BRA",
    "Hammock": "HMK",
    "Mat": "MAT",
    "Rope": "ROP",
    "Sweep": "SWP",
    "Board": "BOD",
    "Basket": "BSK",
    "Canoe": "CNE",
    "Full": "FUL",
    "Gourd": "GOU",
    "Net": "NET",
    "Plate": "PLT",
    "Pot": "POT",
    "Naked": "NKD",
    "Blouse": "BLS",
    "Clothing": "CLT",
    "Cotton": "CTN",
    "Comb": "CMB",
    "Mask": "MSK",
    "Mend": "MND",
    "Sash": "SSH",
    "Sew": "SEW",
    "Skirt": "SKR",
    "Spindlewhorl": "SPW",
    "Thread": "THD",
    "Tie": "TIE",
    "Trousers": "TRS",
    "Weave": "WVE",
    "Thorn": "THN",
    "Flower": "FLW",
    "Leaf": "LEF",
    "Pitch": "PCH",
    "Seed": "SED",
    "Sprout": "SPR",
    "Cane": "CAN",
    "Annatto": "ANN",
    "Avocado": "AVC",
    "Cacao": "CAC",
    "Cassava": "CSV",
    "Cedar": "CDR",
    "Ficus": "FCS",
    "Guava": "GVA",
    "Gumbolimbo": "GBL",
    "Oak": "OAK",
    "Pine": "PIN",
    "Silk-cotton tree": "SCT",
    "Soursop": "SRS",
    "Sycamore": "SYC",
    "Willow": "WLW",
    "Blackberry": "BBY",
    "Grape": "GRP",
    "Nettle": "NTL",
    "Squash": "SQH",
    "Sweet potato": "SWP",
    "Tomato": "TMT",
    "Vine": "VIN",
    "Chilli": "CHI",
    "Clover": "CLV",
    "Fern": "FRN",
    "Goosefoot": "GSF",
    "Marigold": "MGL",
    "Nightshade": "NGS",
    "Onion": "ONI",
    "Pigweed": "PGW",
    "Pot-herbs": "PHB",
    "Purslane": "PRS",
    "Saltwort": "SLW",
    "Rattlepod": "RTP",
    "Tobacco": "TBC",
    "Reed": "RED",
    "Prickly pear": "PPR",
    "Bromelia": "BRM",
    "Century plant": "CPL",
    "Pineapple": "PNA",
    "Yucca": "YCA",
    "Moss": "MOS",
    "Chew": "CHW",
    "Cook": "COK",
    "Drink": "DRK",
    "Eat": "EAT",
    "Hunger": "HNG",
    "Raw": "RAW",
    "Roast": "RST",
    "Tamale": "TML",
    "Toast": "TST",
    "Swallow": "SWL",
    "Tasteless": "TSL",
    "Bad-smelling": "BSM",
    "Bitter": "BTR",
    "Salty": "SLT",
    "Smell": "SML",
    "Sour": "SOR",
    "Awake": "AWK",
    "Begin": "BGN",
    "Bubble": "BBL",
    "Close eyes": "CLE",
    "End": "END",
    "Fat": "FAT",
    "Grow": "GRW",
    "Rest": "RST",
    "Sleep": "SLP",
    "Snore": "SNR",
    "Sweat": "SWT",
    "Tired": "TRD",
    "Arrive here": "ARH",
    "Arrive there": "ART",
    "Come": "COM",
    "Crawl": "CRL",
    "Jump": "JMP",
    "Go back": "GBK",
    "Go by": "GBY",
    "Go down": "GDN",
    "Go in": "GIN",
    "Go out": "GOT",
    "Move": "MOV",
    "No Llegar": "NLL",
    "Run": "RUN",
    "Swim": "SWM",
    "Turn": "TRN",
    "Choke": "CHK",
    "Cough": "CGH",
        "Die": "DIE",
    "Itch": "ITH",
    "Mange": "MNG",
    "Pain": "PAN",
    "Rot": "ROT",
    "Sore": "SOR",
    "Swell": "SWL",
    "Medicine": "MED",
    "Witchcraft": "WCF",
    "Smooth": "SMT",
    "Not heavy": "NHV",
    "Big its foot": "BIF",
    "Big": "BIG",
    "Deep": "DEP",
    "Fine": "FIN",
    "Hard": "HRD",
    "Heavy": "HVY",
    "Little": "LTL",
    "Long": "LNG",
    "Loose": "LOS",
    "Near": "NER",
    "Not erg-strength": "NES",
    "Soft": "SFT",
    "Sticky": "STK",
    "Thick": "THK",
    "Thin": "THN",
    "Ball-shaped": "BSH",
    "Be there": "BTH",
    "Bend": "BND",
    "Dish-shaped": "DSH",
    "Face up": "FUP",
    "Hanging": "HNG",
    "Lying": "LYG",
    "Open": "OPN",
    "Pointed": "PTD",
    "Raise": "RAS",
    "Standing": "STD",
    "Yawn": "YWN",
    "All": "ALL",
    "Yesterday": "YST",
    "160": "ONS", # one sixty
    "400": "FHD", # four hundred
    "Eight": "EGT",
    "Eighteen": "ETN",
    "Eleven": "ELV",
    "Fifteen": "FTN",
    "Five": "FIV",
    "Four": "FOR",
    "Fourteen": "FRT",
    "How much": "HWM",
    "How many": "HWN",
    "Nine": "NIN",
    "Nineteen": "NTN",
    "Ochenta": "OCH",
    "One": "ONE",
    "One year ago": "OYA",
    "Seventeen": "SVT",
    "Six": "SIX",
    "Sixteen": "STN",
    "Ten": "TEN",
    "Thirteen": "THT",
    "Three": "THR",
    "Twelve": "TWL",
    "Two": "TWO",
    "Two hundred": "THD",
    "Veintena": "VTN"
}

categories = {
   "Kinship & Social Organization": "KSO",
   "Thought & Feeling/Perception & Evaluation": "TFP", 
   "Color": "CLR",
   "Body Parts and Other Parts; Body Processes": "BPP",
   "Animal Parts": "ANP",
   "Location": "LOC",
   "Earth": "ERT",
   "Sky": "SKY", 
   "Fire": "FIR",
   "Water & Liquids": "WAL",
   "Mammals": "MML",
   "Birds": "BRD",
   "Reptiles": "REP",
   "Turtles": "TRT",
   "Snakes": "SNK",
   "Lizards": "LZD",
   "Batrachians": "BTR",
   "Fish": "FSH",
   "Mollusks": "MLK",
   "Bugs": "BUG",
   "Speech & Interaction": "SPI",
   "Play, Dance, Music": "PDM",
   "Trade & Property": "TRP",
   "Manipulation": "MAN",
   "Tools": "TLS",
   "Buildings": "BLD",
   "Furniture": "FRN",
   "Containers": "CNT",
   "Clothing & Adornment": "CAD",
   "Agriculture": "AGR",
   "Plant Parts": "PLT",
   "Maize": "MZE",
   "Beans": "BNS",
   "Trees": "TRS",
   "Palms": "PLM",
   "Vines": "VNS",
   "Herbs": "HRB",
   "Grasses": "GRS",
   "Pineapples": "PNP",
   "Fungus": "FNG",
   "Eating": "EAT",
   "Taste": "TST",
   "Life & Existence": "LFE",
   "Movement": "MOV",
   "Sickness": "SCK",
   "Magic": "MGC",
   "Quality": "QLT",
   "Shape": "SHP",
   "Quantity": "QTY",
   "Numerals": "NUM",
   "Grammar": "GRM"
}



def read_file(file_name, sheet_name):
    return pd.read_excel(file_name, sheet_name)

def capitalize_words(text):
    parts = text.split('&')
    capitalized_parts = [part.strip().capitalize() for part in parts]
    return ' & '.join(capitalized_parts)

def create_df(df):
    mapping_dict = dict()
    section = 1  # Start with section 1
    subsection = 1  # Start with subsection 1
    
    for index, row in df.iterrows():
        main_category = row['Kaufman Categories']
        sub_category_list = row['Sub Categories']
        if pd.isna(sub_category_list):
            continue
            
        sub_categories = sub_category_list.split(",")
        for sub_category in sub_categories:
            sub_category = capitalize_words(sub_category.strip().lower())
            numeral_id = f"{section}.{subsection}"
            mapping_dict[sub_category] = {
                'category': main_category,
                'id': numeral_id
            }
            subsection += 1
        section += 1
        subsection = 1  # Reset subsection for new main category
            
    return mapping_dict

def create_combined_abbreviations(mapping_dict, categories, abbreviations):
    combined_abbr = {}
    
    for word, abbr in abbreviations.items():
        # Find the category for this word from mapping_dict
        if word in mapping_dict:
            main_category = mapping_dict[word]['category']
            if main_category in categories:
                combined_abbr[word] = f"{categories[main_category]}_{abbr}"
            else:
                combined_abbr[word] = abbr
        else:
            combined_abbr[word] = abbr

    return combined_abbr

def main():
    file_name = r"C:\Users\kevin barcenas\Downloads\MAYALEX_Workflow\MAYALEX_Workflow\Categories\Kaufman_Semantic_Tags.xlsx"
    df = read_file(file_name, sheet_name="Sheet1")
    mapping = create_df(df)
    
    # Create combined abbreviations
    combined_abbreviations = create_combined_abbreviations(mapping, categories, abbreviations)
    
    # Create DataFrame for Excel export with combined abbreviations
    excel_data = []
    for sub_category, info in mapping.items():
        excel_data.append({
            'ID': info['id'],
            'Sub Category': sub_category,
            'Main Category': info['category'],
            'Combined Abbreviation': combined_abbreviations.get(sub_category, '')
        })
    
    output_df = pd.DataFrame(excel_data)
    output_df.to_excel('category_mappings2.xlsx', index=False)
    print("Excel file created with mappings and combined abbreviations")

if __name__ == "__main__":
    main()